spring.application.name=securitydemo

spring.datasource.url=jdbc:mysql://localhost:3306/securitydemospring?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Danidu#678@mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8080
spring.security.user.name=admin
spring.security.user.password=admin123

spring.session.jdbc.initialize-schema=always
server.servlet.session.timeout=30m